services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "3000:3000"
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"