version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: insecure-bank
      - aws-ecs/deploy-service-update:
          cluster: insecure-bank
          family: insecure-bank-service
          requires:
            - aws-ecr/build-and-push-image