version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          override-ci-command: npm install
  run-task:
    docker:
      - image: node:latest
    steps:
      - aws-ecs/run-task:
          cluster: insecure-bank
          task-definition: insecure-bank
workflows:
  build_and_deploy:
    jobs:
      - build
      - run-task:
          requires:
            - build