version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          region: us-east-1
          registry-id: AWS_ECR_REGISTRY_ID
          repo: insecure-bank
          tag: latest
      - aws-ecs/deploy-service-update:
          cluster: insecure-bank
          container-image-name-updates: container=insecure-bank,tag=latestx
          family: insecure-bank-service
          requires:
            - aws-ecr/build-and-push-image