version: 2.1
orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0.0
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          override-ci-command: npm install
  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
        at: ~/project
      - heroku/deploy-via-git
          force: true
workflows:
  test_my_app:
    jobs:
      - build
      - deploy