on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Web Image
      run: docker build -t insecurebank .
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v2.1.0
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
    - name: Push Web to ECR
      run: |
        docker tag insecurebank ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/insecurebank:latest
        docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/insecurebank:latest