name: Login to ECR
id: ecr
uses: jwalton/gh-ecr-login@v2.1.0
with:
  access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  region: us-east-1
name: Push to ECR
run: |
  docker tag my-image ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/my-image:latest
  docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/my-image:v1